# Task 1 - Your task is to boil caesium

## caesium

In [1]:
from scienceworld import ScienceWorldEnv
import re

import pandas as pd

Parameter containing:
tensor([[2.0000],
        [3.0000],
        [1.5000],
        [0.5000]], requires_grad=True)


In [152]:
weight = torch.tensor([[2.], [3.], [1.5], [0.5]])
print(weight.size())
x * weight

torch.Size([4, 1])


tensor([[2.0000, 4.0000, 6.0000],
        [3.0000, 6.0000, 9.0000],
        [1.5000, 3.0000, 4.5000],
        [0.5000, 1.0000, 1.5000]])

In [97]:
input_embeddings = torch.ones(1, 10, 1)
ff_outputs = torch.nn.Linear(1, 1)(input_embeddings)
ff_outputs

tensor([[[0.8160],
         [0.8160],
         [0.8160],
         [0.8160],
         [0.8160],
         [0.8160],
         [0.8160],
         [0.8160],
         [0.8160],
         [0.8160]]], grad_fn=<ViewBackward0>)

In [45]:
inv = "In your inventory, you see:\n\tan orange\n\ta thermometer, currently reading a temperature of 10 degrees celsius\n"


def parse_inventory(inventory: str) -> list[str]:
    x = re.search(r"(?:In your inventory, you see:)([\S\s]*)", inventory)
    obs_split = []
    if x is not None:
        #print(x.groups())
        objects = x.groups()[0]
        obs_split = [f"In your inventory, you see {obs.strip()}" for obs in objects.split('\n') if len(obs.strip()) > 0]

    return obs_split


def parse(info: dict, observation: str) -> list[str]:
    x = re.search(r"([\S\s]*?)(?:In it, you see:)([\S\s]*?)(?:You also see:)([\S\s]*)", info['look'])
    if x == None:
        x = re.search(r"([\S\s]*?)(?:Here you see:)([\S\s]*?)(?:You also see:)([\S\s]*)", info['look'])
    groups = x.groups()

    location = groups[0]
    objects = groups[1]
    doors = groups[2]

    loc_split = [location.strip()]
    obs_split = [obs.strip() for obs in objects.split('\n') if len(obs.strip()) > 0]
    obs_split = [f"You see {obs}" for obs in obs_split]
    doors_split = [door.strip() for door in doors.split('\n') if len(door.strip()) > 0]
    inventory_items = parse_inventory(info['inv'])
    return loc_split + obs_split + doors_split + inventory_items + [observation]


parse(info, observation)

NameError: name 'info' is not defined

In [21]:
env = ScienceWorldEnv("", "", envStepLimit=100)
#task_name = 'find-non-living-thing'
task_name = 'boil'
#

env.load(task_name, 0)

all_beliefs = []
all_actions = []

for variation in env.getVariationsTrain():
    env.load(task_name, variation)
    goal = env.getTaskDescription().split('.')[0]
    goal = goal.replace(" ", "_").lower()
    task_df = pd.read_csv(f"../plans/plans_csv/task-1-boil/{goal}/{variation}.csv")
    plan = task_df['action']

    #print(env.getTaskDescription())
    #print(env.getTaskDescription().replace(". First, focus on the thing. Then,", "").replace("move", "by moving"))

    # Reset the environment
    observation, info = env.reset()
    for i, action in enumerate(plan):
        action = action.replace("green house", "greenhouse")
        observation, reward, isCompleted, info = env.step(action)
        beliefs = parse(info, observation)
        for b in beliefs:
            if b not in all_beliefs:
                all_beliefs.append(b)
        for a in info['valid']:
            if a not in all_actions:
                all_actions.append(a)
        #print(f"---- Step {i} | action: {action} | Finish {isCompleted} | reward {reward} -----")
        #print(observation)
    #print(info['look'])
    print(f"{variation} - Finished: {isCompleted}")
    #print(env.getGoalProgressStr())

0 - Finished: True
1 - Finished: True
2 - Finished: True
3 - Finished: True
4 - Finished: True
5 - Finished: True
6 - Finished: True
7 - Finished: True
8 - Finished: True
9 - Finished: True
10 - Finished: True
11 - Finished: True
12 - Finished: True
13 - Finished: True


In [22]:
len(all_beliefs), len(all_actions)

(265, 8881)

In [7]:
all_goals = []
for v in env.getVariationsTest():
    env.load(task_name, v)
    goal = env.getTaskDescription().replace(". First, focus on the thing. Then,", "").replace("move", "by moving")
    all_goals.append({'goal': goal})

pd.DataFrame(all_goals).drop_duplicates()

goal
0   Your task is to find a(n) non-living thing by ...
1   Your task is to find a(n) non-living thing by ...
2   Your task is to find a(n) non-living thing by ...
3   Your task is to find a(n) non-living thing by ...
4   Your task is to find a(n) non-living thing by ...
5   Your task is to find a(n) non-living thing by ...
6   Your task is to find a(n) non-living thing by ...
7   Your task is to find a(n) non-living thing by ...
8   Your task is to find a(n) non-living thing by ...
9   Your task is to find a(n) non-living thing by ...
10  Your task is to find a(n) non-living thing by ...
11  Your task is to find a(n) non-living thing by ...
12  Your task is to find a(n) non-living thing by ...
13  Your task is to find a(n) non-living thing by ...
14  Your task is to find a(n) non-living thing by ...
15  Your task is to find a(n) non-living thing by ...
16  Your task is to find a(n) non-living thing by ...
17  Your task is to find a(n) non-living thing by ...
18  Your task is to find a(n) non-living thing by ...
19  Your task is to find a(n) non-living thing by ...
20  Your task is to find a(n) non-living thing by ...
21  Your task is to find a(n) non-living thing by ...
22  Your task is to find a(n) non-living thing by ...
23  Your task is to find a(n) non-living thing by ...
24  Your task is to find a(n) non-living thing by ...
25  Your task is to find a(n) non-living thing by ...
26  Your task is to find a(n) non-living thing by ...
27  Your task is to find a(n) non-living thing by ...
28  Your task is to find a(n) non-living thing by ...
29  Your task is to find a(n) non-living thing by ...